version: '3.8'

services:
  db:
    image: postgres:16-alpine  
    container_name: siprems-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: siprems_db
    ports:
      - "5432:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data #

volumes:
  pgdata:
    